commerce_payment.commerce_payment_gateway.plugin.rocketfuel:
  type: commerce_payment_gateway_configuration
  mapping:
    password:
      type: string
      label: 'Secret key'
    email:
      type: string
      label: 'Email'
    public_key:
      type: string
      label: 'Public Key'
    environment:
      type: string
      label: 'Environment'
    merchant_id:
      type: string
      label: 'Merchant ID'